const ClubPlayers = [
  {
    id: 1,
    name: "Joshua Amos",
    position: "Defence",
    influence: "0",
  },
  {
    id: 2,
    name: "Kieran Busby",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 3,
    name: "Hayden Dickinson",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 4,
    name: "Billy Hewitt",
    position: "Striker",
    influence: "0",
  },
  {
    id: 5,
    name: "Kyle Lawes",
    position: "Defence",
    influence: "0",
  },
  {
    id: 6,
    name: "Kieran Nesbitt",
    position: "Striker",
    influence: "0",
  },
  {
    id: 7,
    name: "Josh Porter",
    position: "Striker",
    influence: "0",
  },
  {
    id: 8,
    name: "Arjun Singh Parker",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 9,
    name: "Elliott Wragg",
    position: "Defender",
    influence: "0",
  },
  {
    id: 10,
    name: "Sam Ballard",
    position: "Defence",
    influence: "0",
  },
  {
    id: 11,
    name: "Daniel Buxton",
    position: "Goalkeeper",
    influence: "0",
  },
  {
    id: 12,
    name: "Ian Evans",
    position: "Striker",
    influence: "0",
  },
  {
    id: 13,
    name: "Ryan Hinsley",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 14,
    name: "Michael Loftus",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 15,
    name: "Kallum O'Reilly",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 16,
    name: "Owen Porter",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 17,
    name: "Kieran Snow",
    position: "Defence",
    influence: "0",
  },
  {
    id: 18,
    name: "Sean Yallop",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 19,
    name: "Jayden Bevan",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 20,
    name: "Joe Clarke",
    position: "Goalkeeper",
    influence: "0",
  },
  {
    id: 21,
    name: "Harrison Fenner",
    position: "Striker",
    influence: "0",
  },
  {
    id: 22,
    name: "Ethan Jay Dickinson",
    position: "Defender",
    influence: "0",
  },
  {
    id: 23,
    name: "Jack Matthews",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 24,
    name: "Ruben Paulino",
    position: "Defence",
    influence: "0",
  },
  {
    id: 25,
    name: "Samuel Roe",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 26,
    name: "Jake Talbot",
    position: "Striker",
    influence: "0",
  },
  {
    id: 27,
    name: "Liam Brooks",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 28,
    name: "Josh Deaves",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 29,
    name: "Charlie Gaston",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 30,
    name: "Cameron Jones",
    position: "Defender",
    influence: "0",
  },
  {
    id: 31,
    name: "David Mortiboys",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 32,
    name: "Conor Pollard",
    position: "Midfield",
    influence: "0",
  },
  {
    id: 33,
    name: "Jordan Scialdone",
    position: "Defence",
    influence: "0",
  },
  {
    id: 34,
    name: "Jake Webb",
    position: "Midfield",
    influence: "0",
  },
];

export default ClubPlayers